version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    env_file:
      - example.env
    environment:
      - KNN_MIN_SCORE=${KNN_MIN_SCORE-0.94}
      - IS_EMBEDDING=${IS_EMBEDDING-true}
      - GCP_LOG_METRICS_ENABLED=False
      - ENTITY_EMBEDDING=${ENTITY_EMBEDDING-False}
      - LLM_MODEL_CONFIG_OLLAMA_LLAMA3=${LLM_MODEL_CONFIG_OLLAMA_LLAMA3-}
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL-http://host.docker.internal:11434}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL-all-minilm}
      - EMBEDDING_PROVIDER=${EMBEDDING_PROVIDER-ollama}
    container_name: backend
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "8000:8000"
    networks:
      - net

networks:
  net:
